CREATE DATABASE HOTEL;

USE HOTEL;
/*
    Este proyecto corresponde a una base de datos
    para administrar las habitaciones de un hotel.
*/
CREATE TABLE HABITACIONES
(
ID_HABITACION INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NUMERO_HABITACION INT  NOT NULL,
TIPO_HABITACION VARCHAR(60) NOT NULL,
PRECIO_POR_NOCHE INT NOT NULL,
CAPACIDAD_PERSONAS INT NOT NULL,
PISO_HABITACION INT NOT NULL,
ESTADO_HABITACION VARCHAR(60) NOT NULL,
FECHA_DE_REGISTROS DATE  NULL
);

-- INSERTAR HABITACIONES

INSERT INTO HABITACIONES 
(NUMERO_HABITACION, TIPO_HABITACION, PRECIO_POR_NOCHE, CAPACIDAD_PERSONAS, PISO_HABITACION, ESTADO_HABITACION, FECHA_DE_REGISTROS)
VALUES  (101, 'Individual', 40000, 1, 1, 'Disponible', '2026-04-01'),
         (2, 'Individual', 40000, 1, 1, 'Disponible', '2026-08-15'),
         (3, 'Individual', 40000, 1, 1, 'Disponible', '2026-01-30'),
         (323, 'Individual', 40000, 1, 1, 'Disponible', '2026-05-20'),
         (65, 'Individual', 40000, 1, 1, 'Disponible', '2026-02-10');

-- CONSULTAR HABITACIONES DISPONIBLES

SELECT NUMERO_HABITACION,TIPO_HABITACION,PRECIO_POR_NOCHE FROM HABITACIONES
WHERE ESTADO_HABITACION = 'Disponible' ;


-- CONSULTAR HABITACIONES SOBRE $50.000

SELECT PRECIO_POR_NOCHE FROM HABITACIONES
WHERE PRECIO_POR_NOCHE > 50000;

-- ACTUALIZAR HABITACIÓN

UPDATE HABITACIONES
SET TIPO_HABITACION = 'Doble',
       PRECIO_POR_NOCHE = 60000
 WHERE NUMERO_HABITACION = 2;

 -- COMPROBAR ACTUALIZACIÓN

SELECT * FROM HABITACIONES
WHERE NUMERO_HABITACION = 2;

-- ELIMINAR HABITACIÓN

DELETE FROM HABITACIONES 
WHERE NUMERO_HABITACION = 65;